### ISSUE TITLE
Make a new LMI_HOLD function

### ISSUE THREAD

**Issue by shamarin** [dercoder/omnipay-webmoney#4]
Now a new function is available for WebMoney merchant LMI_HOLD (reservation or holding of webmoney for some amount of days) http://wiki.webmoney.ru/projects/webmoney/wiki/%D0%A5%D0%BE%D0%BB%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B0_%D1%87%D0%B5%D1%80%D0%B5%D0%B7_Web_Merchant_Interface. Please, realise it in omnipay-webmoney interface.

**Comment by dercoder** [comment]
Please add this feature an do a PR

**Comment by dercoder** [comment]
Show me your code pls

**Comment by shamarin** [comment]
I didn't have any code. I can translate to you the WebMoney wiki article for new function.

**Comment by dercoder** [comment]
Currently i have no time to add this feature. So if you want it, you have to add it by your own

**Comment by shamarin** [comment]
Now i did it by this code in PurchaseRequest.php:
return array(
            'LMI_PAYEE_PURSE' => $this->getMerchantPurse(),
            'LMI_PAYMENT_AMOUNT' => $this->getAmount(),
            'LMI_PAYMENT_NO' => $this->getTransactionId(),
            'LMI_PAYMENT_DESC_BASE64' => base64_encode($this->getDescription()),
            'LMI_SIM_MODE' => $this->getTestMode() ? '2' : '0',
            'LMI_RESULT_URL' => $this->getNotifyUrl(),
            'LMI_SUCCESS_URL' => $this->getReturnUrl(),
            'LMI_SUCCESS_METHOD' => $this->getReturnMethod(),
            'LMI_FAIL_URL' => $this->getCancelUrl(),
            'LMI_FAIL_METHOD' => $this->getCancelMethod(),
            'LMI_HOLD' => '0',
LMI_HOLD is hold function due to WebMoney Merchant documentary, but i didn't know how to make a function of setting number of days in LMI_HOLD. I set it to deault value 'LMI_HOLD' => '0', so it would be 1 day as in example of WebMoney Merchant. Please check it.

**Comment by dercoder** [comment]
So possible values for LMI_HOLD are 0 or 1. Default 0. Right?

**Comment by shamarin** [comment]
Yes, default is 0 (24 hours). And LMI_HOLD value is number of days for holding money without commision on moneyback. So LMI_HOLD could be any number of days - deault is 0 (24 hour) and 1, 2 ,3 and so on.

**Comment by dercoder** [comment]
I understand

**Comment by shamarin** [comment]
LMI_HOLD meens that in value of this days (deafult 24 hours) money is holded. And if the merchant didn't accept transaction in those period of time (days) those money will be backed to purchaser without any commision from WebMoney.

**Comment by shamarin** [comment]
I setup it as 24 hours in message/PurchaseRequest.php file by this code:
return array(
'LMI_PAYEE_PURSE' => $this->getMerchantPurse(),
'LMI_PAYMENT_AMOUNT' => $this->getAmount(),
'LMI_PAYMENT_NO' => $this->getTransactionId(),
'LMI_PAYMENT_DESC_BASE64' => base64_encode($this->getDescription()),
'LMI_SIM_MODE' => $this->getTestMode() ? '2' : '0',
'LMI_RESULT_URL' => $this->getNotifyUrl(),
'LMI_SUCCESS_URL' => $this->getReturnUrl(),
'LMI_SUCCESS_METHOD' => $this->getReturnMethod(),
'LMI_FAIL_URL' => $this->getCancelUrl(),
'LMI_FAIL_METHOD' => $this->getCancelMethod(),
'LMI_HOLD' => '0',

**Comment by dercoder** [comment]
Please try my latest commit. 
getHold() and setHold() functions have been added now

**Comment by shamarin** [comment]
Ok. Will check. Thanks.

**Comment by dercoder** [comment]
Does it work?

**Comment by SilverFire** [comment]
I think we can close this one
